version: '3'

services:
  nginx:
    image: nginx
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - laravel
    container_name: nginx

  laravel:
    image: mgonzalezbaile/php-fpm-dev:7.4
    user: "${UID}:${GID}"
    container_name: laravel
    working_dir: /srv/app
    environment:
      COMPOSER_HOME: /srv/app/.composer
    volumes:
      - .:/srv/app
