version: '3'

services:
  nginx:
    image: nginx
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - laravel
    container_name: nginx

  laravel:
    build:
      dockerfile: Dockerfile
      context: .
    user: "${UID}:${GID}"
    container_name: laravel
    working_dir: /srv/app/ddd-app
    environment:
      COMPOSER_HOME: /srv/app/ddd-app/.composer
    volumes:
      - .:/srv/app
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_DATABASE: "test"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
